# Generated by Django 5.2.1 on 2025-12-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=128, null=True)),
                ("last_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "sponsor1_email",
                    models.CharField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "sponsor2_email",
                    models.CharField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
